# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_launcher_node.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(773, 426)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabLaunch = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabLaunch.setFont(font)
        self.tabLaunch.setObjectName(_fromUtf8("tabLaunch"))
        self.gridLayout = QtGui.QGridLayout(self.tabLaunch)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.vLayoutLaunchList = QtGui.QVBoxLayout()
        self.vLayoutLaunchList.setObjectName(_fromUtf8("vLayoutLaunchList"))
        self.hLayoutListHeader = QtGui.QHBoxLayout()
        self.hLayoutListHeader.setObjectName(_fromUtf8("hLayoutListHeader"))
        self.labelLaunchListHeader = QtGui.QLabel(self.tabLaunch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLaunchListHeader.sizePolicy().hasHeightForWidth())
        self.labelLaunchListHeader.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelLaunchListHeader.setFont(font)
        self.labelLaunchListHeader.setObjectName(_fromUtf8("labelLaunchListHeader"))
        self.hLayoutListHeader.addWidget(self.labelLaunchListHeader, 0, QtCore.Qt.AlignVCenter)
        self.labelListInfo = QtGui.QLabel(self.tabLaunch)
        self.labelListInfo.setObjectName(_fromUtf8("labelListInfo"))
        self.hLayoutListHeader.addWidget(self.labelListInfo, 0, QtCore.Qt.AlignVCenter)
        self.btnClearLaunchList = QtGui.QPushButton(self.tabLaunch)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/New document.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearLaunchList.setIcon(icon)
        self.btnClearLaunchList.setObjectName(_fromUtf8("btnClearLaunchList"))
        self.hLayoutListHeader.addWidget(self.btnClearLaunchList)
        self.vLayoutLaunchList.addLayout(self.hLayoutListHeader)
        self.robotList = QtGui.QListWidget(self.tabLaunch)
        self.robotList.setObjectName(_fromUtf8("robotList"))
        item = QtGui.QListWidgetItem()
        self.robotList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.robotList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.robotList.addItem(item)
        self.vLayoutLaunchList.addWidget(self.robotList)
        self.hLayoutAddRobot = QtGui.QHBoxLayout()
        self.hLayoutAddRobot.setObjectName(_fromUtf8("hLayoutAddRobot"))
        self.comboBoxRobotType = QtGui.QComboBox(self.tabLaunch)
        self.comboBoxRobotType.setMinimumSize(QtCore.QSize(153, 0))
        self.comboBoxRobotType.setObjectName(_fromUtf8("comboBoxRobotType"))
        self.comboBoxRobotType.addItem(_fromUtf8(""))
        self.comboBoxRobotType.addItem(_fromUtf8(""))
        self.comboBoxRobotType.addItem(_fromUtf8(""))
        self.hLayoutAddRobot.addWidget(self.comboBoxRobotType)
        self.spinBoxRobotID = QtGui.QSpinBox(self.tabLaunch)
        self.spinBoxRobotID.setPrefix(_fromUtf8(""))
        self.spinBoxRobotID.setObjectName(_fromUtf8("spinBoxRobotID"))
        self.hLayoutAddRobot.addWidget(self.spinBoxRobotID)
        self.checkBoxSFMMPDM = QtGui.QCheckBox(self.tabLaunch)
        self.checkBoxSFMMPDM.setObjectName(_fromUtf8("checkBoxSFMMPDM"))
        self.hLayoutAddRobot.addWidget(self.checkBoxSFMMPDM)
        self.btnAddRobot = QtGui.QPushButton(self.tabLaunch)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddRobot.setIcon(icon1)
        self.btnAddRobot.setObjectName(_fromUtf8("btnAddRobot"))
        self.hLayoutAddRobot.addWidget(self.btnAddRobot)
        self.vLayoutLaunchList.addLayout(self.hLayoutAddRobot)
        self.horizontalLayout.addLayout(self.vLayoutLaunchList)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelStatusTitle = QtGui.QLabel(self.tabLaunch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatusTitle.sizePolicy().hasHeightForWidth())
        self.labelStatusTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelStatusTitle.setFont(font)
        self.labelStatusTitle.setObjectName(_fromUtf8("labelStatusTitle"))
        self.verticalLayout.addWidget(self.labelStatusTitle)
        self.labelStatus = QtGui.QLabel(self.tabLaunch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelStatus.setFont(font)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.verticalLayout.addWidget(self.labelStatus)
        self.labelStatus_2 = QtGui.QLabel(self.tabLaunch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus_2.sizePolicy().hasHeightForWidth())
        self.labelStatus_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelStatus_2.setFont(font)
        self.labelStatus_2.setText(_fromUtf8(""))
        self.labelStatus_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/How-to.png")))
        self.labelStatus_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus_2.setObjectName(_fromUtf8("labelStatus_2"))
        self.verticalLayout.addWidget(self.labelStatus_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.btnShutdown = QtGui.QPushButton(self.tabLaunch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShutdown.sizePolicy().hasHeightForWidth())
        self.btnShutdown.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Abort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShutdown.setIcon(icon2)
        self.btnShutdown.setObjectName(_fromUtf8("btnShutdown"))
        self.verticalLayout.addWidget(self.btnShutdown)
        self.btnLaunch = QtGui.QPushButton(self.tabLaunch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLaunch.sizePolicy().hasHeightForWidth())
        self.btnLaunch.setSizePolicy(sizePolicy)
        self.btnLaunch.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLaunch.setIcon(icon3)
        self.btnLaunch.setObjectName(_fromUtf8("btnLaunch"))
        self.verticalLayout.addWidget(self.btnLaunch)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLaunch, _fromUtf8(""))
        self.tabEditDockingStation = QtGui.QWidget()
        self.tabEditDockingStation.setObjectName(_fromUtf8("tabEditDockingStation"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabEditDockingStation)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vLayoutDockingStation = QtGui.QVBoxLayout()
        self.vLayoutDockingStation.setObjectName(_fromUtf8("vLayoutDockingStation"))
        self.hLayoutRobotType = QtGui.QHBoxLayout()
        self.hLayoutRobotType.setObjectName(_fromUtf8("hLayoutRobotType"))
        self.labelRobotType = QtGui.QLabel(self.tabEditDockingStation)
        self.labelRobotType.setObjectName(_fromUtf8("labelRobotType"))
        self.hLayoutRobotType.addWidget(self.labelRobotType)
        self.comboBoxRobotType_2 = QtGui.QComboBox(self.tabEditDockingStation)
        self.comboBoxRobotType_2.setMinimumSize(QtCore.QSize(153, 0))
        self.comboBoxRobotType_2.setObjectName(_fromUtf8("comboBoxRobotType_2"))
        self.comboBoxRobotType_2.addItem(_fromUtf8(""))
        self.comboBoxRobotType_2.addItem(_fromUtf8(""))
        self.comboBoxRobotType_2.addItem(_fromUtf8(""))
        self.hLayoutRobotType.addWidget(self.comboBoxRobotType_2)
        self.vLayoutDockingStation.addLayout(self.hLayoutRobotType)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.vLayoutDockingStation.addItem(spacerItem1)
        self.labelDockingStationTitle = QtGui.QLabel(self.tabEditDockingStation)
        self.labelDockingStationTitle.setObjectName(_fromUtf8("labelDockingStationTitle"))
        self.vLayoutDockingStation.addWidget(self.labelDockingStationTitle)
        self.hLayoutDockingStationOrigin = QtGui.QHBoxLayout()
        self.hLayoutDockingStationOrigin.setObjectName(_fromUtf8("hLayoutDockingStationOrigin"))
        self.labelDockingStationOriginX = QtGui.QLabel(self.tabEditDockingStation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDockingStationOriginX.sizePolicy().hasHeightForWidth())
        self.labelDockingStationOriginX.setSizePolicy(sizePolicy)
        self.labelDockingStationOriginX.setObjectName(_fromUtf8("labelDockingStationOriginX"))
        self.hLayoutDockingStationOrigin.addWidget(self.labelDockingStationOriginX)
        self.doubleSpinBoxDockingStationOriginX = QtGui.QDoubleSpinBox(self.tabEditDockingStation)
        self.doubleSpinBoxDockingStationOriginX.setDecimals(2)
        self.doubleSpinBoxDockingStationOriginX.setMinimum(-100.0)
        self.doubleSpinBoxDockingStationOriginX.setObjectName(_fromUtf8("doubleSpinBoxDockingStationOriginX"))
        self.hLayoutDockingStationOrigin.addWidget(self.doubleSpinBoxDockingStationOriginX)
        self.labelDockingStationOriginY = QtGui.QLabel(self.tabEditDockingStation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDockingStationOriginY.sizePolicy().hasHeightForWidth())
        self.labelDockingStationOriginY.setSizePolicy(sizePolicy)
        self.labelDockingStationOriginY.setObjectName(_fromUtf8("labelDockingStationOriginY"))
        self.hLayoutDockingStationOrigin.addWidget(self.labelDockingStationOriginY)
        self.doubleSpinBoxDockingStationOriginY = QtGui.QDoubleSpinBox(self.tabEditDockingStation)
        self.doubleSpinBoxDockingStationOriginY.setDecimals(2)
        self.doubleSpinBoxDockingStationOriginY.setMinimum(-100.0)
        self.doubleSpinBoxDockingStationOriginY.setObjectName(_fromUtf8("doubleSpinBoxDockingStationOriginY"))
        self.hLayoutDockingStationOrigin.addWidget(self.doubleSpinBoxDockingStationOriginY)
        self.vLayoutDockingStation.addLayout(self.hLayoutDockingStationOrigin)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.vLayoutDockingStation.addItem(spacerItem2)
        self.labelRobotOffsetTitle = QtGui.QLabel(self.tabEditDockingStation)
        self.labelRobotOffsetTitle.setObjectName(_fromUtf8("labelRobotOffsetTitle"))
        self.vLayoutDockingStation.addWidget(self.labelRobotOffsetTitle)
        self.hLayoutRobotOffsetSpacing = QtGui.QHBoxLayout()
        self.hLayoutRobotOffsetSpacing.setObjectName(_fromUtf8("hLayoutRobotOffsetSpacing"))
        self.labelRobotOffsetSpacingX = QtGui.QLabel(self.tabEditDockingStation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRobotOffsetSpacingX.sizePolicy().hasHeightForWidth())
        self.labelRobotOffsetSpacingX.setSizePolicy(sizePolicy)
        self.labelRobotOffsetSpacingX.setObjectName(_fromUtf8("labelRobotOffsetSpacingX"))
        self.hLayoutRobotOffsetSpacing.addWidget(self.labelRobotOffsetSpacingX)
        self.doubleSpinBoxRobotOffsetSpacingX = QtGui.QDoubleSpinBox(self.tabEditDockingStation)
        self.doubleSpinBoxRobotOffsetSpacingX.setDecimals(2)
        self.doubleSpinBoxRobotOffsetSpacingX.setMinimum(-100.0)
        self.doubleSpinBoxRobotOffsetSpacingX.setObjectName(_fromUtf8("doubleSpinBoxRobotOffsetSpacingX"))
        self.hLayoutRobotOffsetSpacing.addWidget(self.doubleSpinBoxRobotOffsetSpacingX)
        self.labelRobotOffsetSpacingY = QtGui.QLabel(self.tabEditDockingStation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRobotOffsetSpacingY.sizePolicy().hasHeightForWidth())
        self.labelRobotOffsetSpacingY.setSizePolicy(sizePolicy)
        self.labelRobotOffsetSpacingY.setObjectName(_fromUtf8("labelRobotOffsetSpacingY"))
        self.hLayoutRobotOffsetSpacing.addWidget(self.labelRobotOffsetSpacingY)
        self.doubleSpinBoxRobotOffsetSpacingY = QtGui.QDoubleSpinBox(self.tabEditDockingStation)
        self.doubleSpinBoxRobotOffsetSpacingY.setDecimals(2)
        self.doubleSpinBoxRobotOffsetSpacingY.setMinimum(-100.0)
        self.doubleSpinBoxRobotOffsetSpacingY.setObjectName(_fromUtf8("doubleSpinBoxRobotOffsetSpacingY"))
        self.hLayoutRobotOffsetSpacing.addWidget(self.doubleSpinBoxRobotOffsetSpacingY)
        self.vLayoutDockingStation.addLayout(self.hLayoutRobotOffsetSpacing)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelRobotsPerRow = QtGui.QLabel(self.tabEditDockingStation)
        self.labelRobotsPerRow.setObjectName(_fromUtf8("labelRobotsPerRow"))
        self.horizontalLayout_2.addWidget(self.labelRobotsPerRow)
        self.spinBoxMaxRobotsPerRow = QtGui.QSpinBox(self.tabEditDockingStation)
        self.spinBoxMaxRobotsPerRow.setMinimum(1)
        self.spinBoxMaxRobotsPerRow.setObjectName(_fromUtf8("spinBoxMaxRobotsPerRow"))
        self.horizontalLayout_2.addWidget(self.spinBoxMaxRobotsPerRow)
        self.vLayoutDockingStation.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vLayoutDockingStation.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.vLayoutDockingStation, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabEditDockingStation, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionSave_file = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_file.setIcon(icon4)
        self.actionSave_file.setObjectName(_fromUtf8("actionSave_file"))
        self.actionLoad_file = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_file.setIcon(icon5)
        self.actionLoad_file.setObjectName(_fromUtf8("actionLoad_file"))
        self.actionQuit_application = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit_application.setIcon(icon6)
        self.actionQuit_application.setObjectName(_fromUtf8("actionQuit_application"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave_file)
        self.menuFile.addAction(self.actionLoad_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_application)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "multi_robot_sim - Launcher GUI", None))
        self.labelLaunchListHeader.setText(_translate("MainWindow", "Launch list", None))
        self.labelListInfo.setText(_translate("MainWindow", "(RMB - remove an item)", None))
        self.btnClearLaunchList.setText(_translate("MainWindow", "  Clear Launch list", None))
        __sortingEnabled = self.robotList.isSortingEnabled()
        self.robotList.setSortingEnabled(False)
        item = self.robotList.item(0)
        item.setText(_translate("MainWindow", "rdg01 - SFMMPDM", None))
        item = self.robotList.item(1)
        item.setText(_translate("MainWindow", "rdg02 - SFMMPDM", None))
        item = self.robotList.item(2)
        item.setText(_translate("MainWindow", "rdg03 - move_base", None))
        self.robotList.setSortingEnabled(__sortingEnabled)
        self.comboBoxRobotType.setItemText(0, _translate("MainWindow", "Ridgeback", None))
        self.comboBoxRobotType.setItemText(1, _translate("MainWindow", "ROSbot", None))
        self.comboBoxRobotType.setItemText(2, _translate("MainWindow", "Husky", None))
        self.checkBoxSFMMPDM.setText(_translate("MainWindow", "SFM-MPDM", None))
        self.btnAddRobot.setText(_translate("MainWindow", "  Add robot", None))
        self.labelStatusTitle.setText(_translate("MainWindow", "Launch status:", None))
        self.labelStatus.setText(_translate("MainWindow", "Awaiting launch...", None))
        self.btnShutdown.setText(_translate("MainWindow", "  Shutdown", None))
        self.btnLaunch.setText(_translate("MainWindow", "  Launch", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLaunch), _translate("MainWindow", "Launch", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabLaunch), _translate("MainWindow", "Launch list and launch control options", None))
        self.labelRobotType.setText(_translate("MainWindow", "Robot type:", None))
        self.comboBoxRobotType_2.setItemText(0, _translate("MainWindow", "Ridgeback", None))
        self.comboBoxRobotType_2.setItemText(1, _translate("MainWindow", "ROSbot", None))
        self.comboBoxRobotType_2.setItemText(2, _translate("MainWindow", "Husky", None))
        self.labelDockingStationTitle.setText(_translate("MainWindow", "Docking station master origin", None))
        self.labelDockingStationOriginX.setText(_translate("MainWindow", "  X:   ", None))
        self.labelDockingStationOriginY.setText(_translate("MainWindow", "  Y:   ", None))
        self.labelRobotOffsetTitle.setText(_translate("MainWindow", "Robot offset spacing", None))
        self.labelRobotOffsetSpacingX.setText(_translate("MainWindow", "  X:   ", None))
        self.labelRobotOffsetSpacingY.setText(_translate("MainWindow", "  Y:   ", None))
        self.labelRobotsPerRow.setText(_translate("MainWindow", "Maximum number of robots per row:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEditDockingStation), _translate("MainWindow", "Docking stations", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabEditDockingStation), _translate("MainWindow", "Adjust docking station origin per robot type", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave_file.setText(_translate("MainWindow", "&Save as", None))
        self.actionLoad_file.setText(_translate("MainWindow", "&Load setup", None))
        self.actionQuit_application.setText(_translate("MainWindow", "&Quit application", None))
        self.actionNew.setText(_translate("MainWindow", "&New...", None))

import images_rc
